@{
    RootModule        = 'DriverAutomationToolCore.psm1'
    ModuleVersion     = '10.0.15.0'
    GUID              = 'a3e0e746-8e3a-4c5b-b8d0-3b2e4f6a9c1d'
    Author            = 'Maurice Daly'
    CompanyName       = 'MSEndpointMgr'
    Copyright         = '(c) Maurice Daly. All rights reserved.'
    Description       = 'Core functions for Driver Automation Tool'
    PowerShellVersion = '5.1'
    FunctionsToExport = @(
        'Write-DATLogEntry',
        'Set-DATRegistryValue',
        'Reset-DATRegistryValues',
        'Get-DATOEMSources',
        'Get-DATOEMModelInfo',
        'Get-DATOEMDownloadLinks',
        'Find-DATLenovoModelType',
        'Invoke-DATContentDownload',
        'Invoke-DATExecutable',
        'Invoke-DATDriverFilePackaging',
        'Invoke-DATOEMDownloadModule',
        'Install-DATDriverPackage',
        'Start-DATModelProcessing',
        'Connect-DATConfigMgr',
        'Get-DATConfigMgrKnownModels',
        'Get-DATSiteCode',
        'Get-DATDistributionPoints',
        'Get-DATDistributionPointGroups',
        'Get-DATLocalSystemTime',
        'New-DATConfigMgrPkg',
        'Publish-DATConfigMgrPkg',
        'Get-DATScriptDirectory',
        'Connect-DATIntuneGraph',
        'Connect-DATIntuneGraphClientCredential',
        'Connect-DATIntuneGraphInteractive',
        'Complete-DATBrowserAuth',
        'Complete-DATDeviceCodeAuth',
        'Test-DATIntunePermissions',
        'Test-DATIntuneAuth',
        'Set-DATIntuneAuthToken',
        'Invoke-DATTokenRefresh',
        'Disconnect-DATIntuneGraph',
        'Invoke-DATGraphRequest',
        'Get-DATIntuneKnownModels',
        'Get-DATIntuneWin32Apps',
        'Get-DATIntuneAppById',
        'Remove-DATIntuneApp',
        'New-DATIntuneWin32App',
        'Get-DATIntuneAuthStatus',
        'New-DATIntuneToastScript',
        'New-DATIntuneInstallScript',
        'New-DATIntuneRequirementScript',
        'New-DATIntuneDetectionScript',
        'New-DATIntuneWinPackage',
        'Get-DATIntuneWinEncryptionInfo',
        'Invoke-DATIntuneWin32AppUpload',
        'Invoke-DATIntunePackageCreation',
        'Set-DATBIOSPassword',
        'Get-DATBIOSPassword',
        'Remove-DATBIOSPassword',
        'Get-DATProxySettings',
        'Get-DATWebRequestProxy',
        'Get-DATHttpClientHandler',
        'Get-DATCurlProxyArgs',
        'Test-DATProxyConnection',
        'Test-DATHPCMSLReady',
        'Search-DATEntraGroups',
        'Set-DATIntuneAppAssignment',
        'Get-DATTelemetryConfig',
        'Test-DATTelemetryEnabled',
        'Get-DATTelemetryId',
        'Get-DATPackageHash',
        'Send-DATTelemetry',
        'Send-DATDriverReport',
        'Send-DATBiosReport',
        'Send-DATSummaryReport',
        'Test-DATTelemetryConnection',
        'Get-DATBiosCatalog',
        'Find-DATBiosPackage',
        'Get-DATFlash64W',
        'Invoke-DATBiosPackaging',
        'Start-DATBiosDownload',
        'Invoke-DATPackageRetention',
        'Send-DATReportIssue',
        'ConvertTo-DATIntuneMinimumOS',
        'Send-DATTeamsNotification',
        'Import-DATBuildConfig',
        'Export-DATBuildConfig',
        'Register-DATScheduledBuild',
        'Unregister-DATScheduledBuild',
        'Get-DATAvailableUpdate',
        'Update-DATApplication'
    )
    VariablesToExport = '*'
    CmdletsToExport   = @()
    AliasesToExport    = @()
}
